// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tepjztxikxkqobhcfovd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlcGp6dHhpa3hrcW9iaGNmb3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNjI4ODIsImV4cCI6MjA4MzkzODg4Mn0.FG98VPxe4Hf_fcaxJ-xt65LJThyCmV-_vMZZxQdYIk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});